baseurl = "/"
languageCode = "en-us"
title = "Jonathan Lamberts"
theme = "hugo-xmin"
googleAnalytics = "UA-113789312-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[params]
    description = "A website built through Hugo and blogdown."
    footer = "jonathan.lamberts@gmail.com | [Github](https://github.com/jlamberts) | [Linkedin](https://www.linkedin.com/in/jonathan-lamberts/)"
