baseurl = "/"
languageCode = "en-us"
title = "Jonathan Lamberts"
theme = "hugo-xmin"
googleAnalytics = "UA-113789312-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params]
    description = "A website built through Hugo and blogdown."
    footer = "[Github](https://github.com/jlamberts) | [Linkedin](https://www.linkedin.com/in/jonathan-lamberts/)"
